<?php

namespace PWE\Core;

require_once dirname(__FILE__) . '/../../PWEUnitTests.php';

/**
 * Test class for AbstractPWECore.
 * Generated by PHPUnit on 2011-09-12 at 01:32:30.
 */
class AbstractPWECoreTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractPWECore
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AbstractPWECoreImpl();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testSetRootDirectory().
     */
    public function testSetRootDirectory() {
        $this->object->setRootDirectory('');
    }

    /**
     * @todo Implement testSetDataDirectory().
     */
    public function testSetDataDirectory() {
        $this->object->setDataDirectory('');
    }

    /**
     * @todo Implement testSetXMLDirectory().
     */
    public function testSetXMLDirectory() {
        $this->object->setXMLDirectory('');
    }

    /**
     * @todo Implement testSetTempDirectory().
     */
    public function testSetTempDirectory() {
        $this->object->setTempDirectory('');
    }

    /**
     * @todo Implement testGetDataDirectory().
     */
    public function testGetDataDirectory() {
        $this->object->getDataDirectory();
    }

    /**
     * @todo Implement testGetXMLDirectory().
     */
    public function testGetXMLDirectory() {
        $this->object->getDataDirectory();
    }

    /**
     * @todo Implement testGetTempDirectory().
     */
    public function testGetTempDirectory() {
        $this->object->getTempDirectory();
    }

    /**
     * @todo Implement testSetDisplayTemplate().
     */
    public function testSetDisplayTemplate() {
        $this->object->setDisplayTemplate('');
    }

    /**
     * @todo Implement testGetDisplayTemplate().
     */
    public function testGetDisplayTemplate() {
        $this->object->getDisplayTemplate();
    }

    /**
     * @todo Implement testGetEmptyTemplate().
     */
    public function testGetEmptyTemplate() {
        $this->object->getEmptyTemplate();
    }

}

class AbstractPWECoreImpl extends AbstractPWECore {
    
}

?>
