<?php

namespace PWE\Modules;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-04 at 15:49:49.
 */
class CMDLineModulesManagerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var CMDLineModulesManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CMDLineModulesManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
