<?php

namespace PWE\Modules;

use PWE\Core\UnitTestPWECore;

require_once dirname(__FILE__) . '/../../PWEUnitTests.php';

/**
 * Test class for PWEModulesManager.
 * Generated by PHPUnit on 2011-09-12 at 13:21:26.
 */
class PWEModulesManagerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PWEModulesManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->pwe = new UnitTestPWECore();
        copy(dirname(__FILE__) . '/registry.xml', $this->pwe->getTempDirectory() . '/eg_globals.xml');
        $this->object = new PWEModulesManager($this->pwe);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGetModuleSettings().
     */
    public function testGetModuleSettings() {
        $this->object->getModuleSettings(__CLASS__);
    }

    /**
     * @todo Implement testGetSingleInstanceModule().
     */
    public function testGetSingleInstanceModule() {
        $this->object->getSingleInstanceModule(__CLASS__);
    }

    /**
     * @todo Implement testGetMultiInstanceModule().
     */
    public function testGetMultiInstanceModule() {
        $a['!a']['class'] = __CLASS__;
        $this->object->getMultiInstanceModule($a);
    }

    public function testRegister() {
        $a['!a']['class'] = __CLASS__;
        $this->object->registerModule(__CLASS__);
    }

}

?>
