language: php

#php:
#  - 5.4
#  - 5.5
#  - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script: vendor/phpunit/phpunit/phpunit --bootstrap test/PWEUnitTests.php --coverage-clover=coverage.xml test

after_success:
  - bash <(curl -s https://codecov.io/bash)