<?php

namespace PWE\Lib\AmCharts;

require_once dirname(__FILE__) . '/../../../PWEUnitTests.php';

/**
 * Test class for AMChartsHelper.
 * Generated by PHPUnit on 2011-09-16 at 20:58:00.
 */
class AMChartsHelperTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AMChartsHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AMChartsHelper(new \PWE\Core\UnitTestPWECore);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGetAmChartsDir().
     */
    public function testGetAmChartsDir() {
        $this->object->getAmChartsDir();
    }

    /**
     * @todo Implement testGetPathTo().
     */
    public function testGetPathTo() {
        $this->object->getPathTo();
    }

    /**
     * @todo Implement testSetup().
     */
    public function testSetup() {
        $regData = array();
        AMChartsHelper::setup($this->object->getPWE(), $regData);
    }

}

?>
