<?php

namespace PWE\Auth;

require_once dirname(__FILE__) . '/../../PWEUnitTests.php';

/**
 * Test class for PWEUserAuthController.
 * Generated by PHPUnit on 2011-09-12 at 12:21:07.
 */
class PWEUserAuthControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PWEUserAuthController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PWEUserAuthControllerImpl();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGetSmartyAllowedMethods().
     */
    public function testGetSmartyAllowedMethods() {
        $this->object->getSmartyAllowedMethods();
    }

    /**
     * @todo Implement testGetAuthControllerInstance().
     */
    public function testGetAuthControllerInstance() {
        $this->object->getPWE()->setURL('/');
        PWEUserAuthController::getAuthControllerInstance($this->object->getPWE());
    }

    /**
     * @todo Implement testGetLevelsUpToAuthNode().
     */
    public function testGetLevelsUpToAuthNode() {
        $this->object->getPWE()->setURL('/');
        $this->object->getLevelsUpToAuthNode();
    }

}

class PWEUserAuthControllerImpl extends PWEUserAuthController {

    public function __construct() {
        parent::__construct(new \PWE\Core\UnitTestPWECore());
    }

    public function getUserID() {
        
    }

    public function getUserName() {
        
    }

    public function handleAuth() {
        
    }

    public function handleLogout() {
        
    }

}

?>
