<?php

namespace PWE\Lib\Doctrine;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-04 at 15:50:10.
 */
class PWEDoctrineLoggerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PWEDoctrineLogger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PWEDoctrineLogger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PWE\Lib\Doctrine\PWEDoctrineLogger::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        
    }

    /**
     * @covers PWE\Lib\Doctrine\PWEDoctrineLogger::startQuery
     * @todo   Implement testStartQuery().
     */
    public function testStartQuery() {
        $this->object->startQuery("");
    }

    /**
     * @covers PWE\Lib\Doctrine\PWEDoctrineLogger::stopQuery
     * @todo   Implement testStopQuery().
     */
    public function testStopQuery() {
        $this->object->stopQuery("");
    }

}
