<?php

namespace PWE\Lib\Smarty;

require_once dirname(__FILE__) . '/../../../PWEUnitTests.php';

/**
 * Test class for SmartyWrapper.
 * Generated by PHPUnit on 2011-09-16 at 20:59:13.
 */
class SmartyWrapperTest extends \PHPUnit_Framework_TestCase implements SmartyAssociative {

    /**
     * @var SmartyWrapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SmartyWrapper(new \PWE\Core\UnitTestPWECore());
        $this->object->addTemplateDir('.');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testSetTemplateFile().
     */
    public function testSetTemplateFile() {
        $this->object->setTemplateFile('');
    }

    /**
     * @todo Implement testFetchAll().
     */
    public function testFetchAll() {
        $this->object->setTemplateFile(__FILE__);
        $this->object->fetchAll();
    }

    /**
     * @todo Implement testRegisterObject().
     */
    public function testRegisterObject() {
        $this->object->registerObject('test', $this);
    }

    public static function getSmartyAllowedMethods() {
        return array();
    }

    /**
     * @todo Implement testSetup().
     */
    public function testSetup() {
        $registerData = array();
        SmartyWrapper::setup(new \PWE\Core\UnitTestPWECore(), $registerData);
    }

}

?>
