<?php

namespace PWE\Modules;

use PWE\Core\UnitTestPWECore;

require_once __DIR__ . '/../../PWEUnitTests.php';

/**
 * Test class for PWEModule.
 * Generated by PHPUnit on 2011-09-12 at 01:32:34.
 */
class PWEModuleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PWEModule
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function test_getBaseLink() {
        $pwe = new UnitTestPWECore();
        $pwe->setStructFile(__DIR__ . '/modulestruct.xml');
        $pwe->setURL('/accept/');
        $this->object = new PWEModuleImpl($pwe);
        $this->assertEquals(".", $this->object->getBaseLink());
    }

    public function test_getBaseLink2() {
        $pwe = new UnitTestPWECore();
        $pwe->setStructFile(__DIR__ . '/modulestruct.xml');
        $pwe->setURL('/accept/123/');
        $this->object = new PWEModuleImpl($pwe);
        $this->assertEquals("./..", $this->object->getBaseLink());
    }

}

class PWEModuleImpl extends WebPWEModule {

    public function getBaseLink() {
        return parent::getBaseLink();
    }

    /**
     * @return void
     */
    public function process()
    {
    }
}

?>
