<?php

namespace PWE\Exceptions;

use PWE\Core\PWELogger;

require_once __DIR__ . '/../../PWEUnitTests.php';

/**
 * Test class for HTTP3xxException.
 * Generated by PHPUnit on 2011-09-12 at 01:32:32.
 */
class HTTP3xxExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var HTTP3xxException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HTTP3xxException("test");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testInst()
    {
        PWELogger::debug("done");
    }

}

