<?php

namespace PWE\Exceptions;

require_once dirname(__FILE__) . '/../../PWEUnitTests.php';

/**
 * Test class for HTTP5xxException.
 * Generated by PHPUnit on 2011-09-12 at 01:32:32.
 */
class HTTP5xxExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HTTP5xxException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTTP5xxException("test");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testInst() {
        \PWE\Core\PWELogger::debug("done");
    }

}

?>
