<?php

namespace PWE\Modules\RedirectAccepted;

require_once dirname(__FILE__) . '/../../../PWEUnitTests.php';

use PWE\Exceptions\HTTP3xxException;

/**
 * Test class for RedirectAccepted.
 * Generated by PHPUnit on 2011-09-16 at 21:00:17.
 */
class RedirectAcceptedTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var RedirectAccepted
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RedirectAccepted(new \PWE\Core\UnitTestPWECore);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testProcess().
     */
    public function testProcess() {
        $this->object->getPWE()->setStructFile(dirname(__FILE__) . '/redirect.xml');
        $this->object->getPWE()->setURL('/param/');
        $_GET['getparam']='test';
        try {
            $this->object->process();
            $this->fail();
        } catch (HTTP3xxException $e) {
            
        }
    }

}

?>
